services:
  postgres_students_db:
    image: postgres
    container_name: postgres_students_db_container
    restart: always
    ports:
      - 4457:5432
    env_file:
      - ./back-end/.env
    volumes:
      - pg_students_db:/var/lib/postegresql/data

  node_students:
    container_name: node_students_container
    build: ./back-end
    image: node_students_image
    ports:
      - 5000:5000
    depends_on:
      - postgres_students_db
    env_file:
      - ./back-end/.env

  react_students:
    container_name: react_students_container
    build: ./front-end
    image: react_students_image
    volumes:
      - build_react:/var/www/html

  nginx_students:
    container_name: nginx_students_container
    build: ./nginx
    image: nginx_students_image
    ports:
      - 8080:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - postgres_students_db
      - node_students
      - react_students
volumes:
  pg_students_db:
  build_react:
